# Test your FastAPI endpoints

# Create a new user
POST http://localhost:8000/api
Content-Type: application/json

{
    "name": "Test Test"
}

###

# Read a user
GET http://localhost:8000/api/6

###

# Update a user
PUT http://localhost:8000/api/6
Content-Type: application/json

{
    "name": "Test 2"
}

###

# Delete a user
DELETE http://localhost:8000/api/6
